<?php
declare(strict_types=1);

/** Builds a realistic, disposable tenant for Stage 3 SQL-read verification. */
require_once __DIR__ . DIRECTORY_SEPARATOR . 'mysql_connection.php';
$slug=$argv[1]??'';
if(!is_string($slug)||!preg_match('/^perf-stage3-[a-z0-9-]+$/',$slug)){fwrite(STDERR,"Use a disposable perf-stage3-* slug.\n");exit(2);}
$root=dirname(__DIR__);$pdo=mysqlMigrationPdo($root);$exists=$pdo->prepare('SELECT 1 FROM institutions WHERE slug=?');$exists->execute([$slug]);if($exists->fetchColumn())throw new RuntimeException('Fixture slug already exists.');
$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));$created=$now->format('Y-m-d H:i:s.u');$start=$now->modify('-30 minutes')->format('Y-m-d H:i:s.u');$end=$now->modify('+90 minutes')->format('Y-m-d H:i:s.u');
$pdo->beginTransaction();try{
    $pdo->prepare('INSERT INTO institutions (name,slug,active,created_at) VALUES (?,?,1,?)')->execute(['Stage 3 Performance Fixture',$slug,$created]);$institutionId=(int)$pdo->lastInsertId();
    $pdo->prepare('INSERT INTO institution_branding (institution_id,display_name,portal_title,logo_path,favicon_path,accent_source_color,primary_color,accent_color,nav_label,assessment_label,footer_primary,footer_secondary,footer_legal,result_sheet_title,newsletter_sender_name,support_email,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)')->execute([$institutionId,'Stage 3 Test','Stage 3 Test CBT','CACSA%20Logo.jpeg','favicon.php','#16774d','#16774d','#105839','Stage 3 Test CBT','Assessment centre','Stage 3 test node','Disposable performance tenant','© {year} Stage 3 Test','Stage 3 Test CBT','Stage 3 Test','stage3@example.invalid',$created]);
    $pdo->prepare('INSERT INTO academic_sessions (institution_id,id,label,is_active,created_at) VALUES (?,\'s3-session\',\'2026/2027\',1,?)')->execute([$institutionId,$created]);$pdo->prepare('INSERT INTO academic_semesters (institution_id,id,session_id,label,is_active,created_at) VALUES (?,\'s3-semester\',\'s3-session\',\'Harmattan Semester\',1,?)')->execute([$institutionId,$created]);
    $pdo->prepare('INSERT INTO courses (institution_id,id,session_id,semester_id,code,title,course_unit,test_max_mark,exam_max_mark,legacy_exam_only,created_at) VALUES (?,\'s3-course\',\'s3-session\',\'s3-semester\',\'S3 101\',\'Performance Data\',3,30,70,0,?)')->execute([$institutionId,$created]);
    $component=$pdo->prepare('INSERT INTO course_components (institution_id,id,course_id,component,code,title,duration_minutes,max_mark,question_count,start_at,end_at,status,legacy_exam_only,created_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');$component->execute([$institutionId,'s3-test','s3-course','test','S3 101','Performance Data',60,30,2,$start,$end,'active',0,$created]);$component->execute([$institutionId,'s3-exam','s3-course','exam','S3 101','Performance Data',90,70,2,$start,$end,'active',0,$created]);
    $pdo->prepare('INSERT INTO roles (institution_id,id,name,description,max_users,system_locked) VALUES (?,\'admin\',\'Admin\',\'Fixture admin\',1000,1)')->execute([$institutionId]);foreach(['overview','students','exams','questions','results','audit','newsletter','settings','roles'] as $permission)$pdo->prepare('INSERT INTO role_permissions (institution_id,role_id,permission) VALUES (?,\'admin\',?)')->execute([$institutionId,$permission]);
    $pdo->prepare('INSERT INTO admin_users (institution_id,id,role_id,name,email,password_hash,active,verified,must_change_password,created_at) VALUES (?,\'s3-admin\',\'admin\',\'Stage 3 Admin\',\'stage3-admin@example.invalid\',NULL,1,1,0,?)')->execute([$institutionId,$created]);$permissions=json_encode(['overview','students','exams','questions','results','audit','newsletter','settings','roles'],JSON_THROW_ON_ERROR);$session=$pdo->prepare('INSERT INTO admin_sessions (institution_id,token_hash,user_id,email,name,role_id,permissions_json,correlation_id,created_at,last_seen_at,expires_at) VALUES (?,?,?,?,?,?,?,?,?,?,?)');for($i=1;$i<=1000;$i++)$session->execute([$institutionId,hash('sha256','stage3-admin-token-'.$i),'s3-admin','stage3-admin@example.invalid','Stage 3 Admin','admin',$permissions,'stage3-'.$i,$created,$created,'2099-12-31 23:59:59.000000']);
    $student=$pdo->prepare('INSERT INTO students (institution_id,id,full_name,matric_number,email,department,active,created_at) VALUES (?,?,?,?,?,?,1,?)');$submission=$pdo->prepare('INSERT INTO component_submissions (institution_id,id,attempt_id,student_id,course_id,component_id,academic_session_id,academic_semester_id,component,status,raw_score,scaled_score,score,submitted_at,course_unit,review_snapshot_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)');
    for($i=1;$i<=300;$i++){ $studentId='s3-student-'.$i;$student->execute([$institutionId,$studentId,'Stage Three Student '.$i,'S3/'.str_pad((string)$i,4,'0',STR_PAD_LEFT),'s3-'.$i.'@example.invalid','Performance',$created]);foreach([['test',30],['exam',70]] as [$kind,$max]){$score=($i*7+($kind==='test'?3:11))%101;$scaled=round($score*$max/100,1);$submitted=$now->modify('-'.($i%120).' days')->format('Y-m-d H:i:s.u');$submission->execute([$institutionId,'s3-submission-'.$kind.'-'.$i,null,$studentId,'s3-course','s3-'.$kind,'s3-session','s3-semester',$kind,'submitted',$score,$scaled,$scaled,$submitted,3,json_encode(['questions'=>[],'integrityEvents'=>[]],JSON_THROW_ON_ERROR)]);}}
    $audit=$pdo->prepare('INSERT INTO audit_events (institution_id,id,timestamp_at,actor_type,actor_id,action_type,target_type,target_id,ip_address,user_agent,outcome,correlation_id,before_after_json,metadata_json) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?)');for($i=1;$i<=3000;$i++){ $studentNumber=(($i-1)%300)+1;$metadata=json_encode(['matricNumber'=>'S3/'.str_pad((string)$studentNumber,4,'0',STR_PAD_LEFT),'course'=>'S3 101','name'=>'Stage Three Student '.$studentNumber],JSON_THROW_ON_ERROR);$audit->execute([$institutionId,'s3-audit-'.$i,$now->modify('-'.($i%180).' days')->format('Y-m-d H:i:s.u'),$i%3===0?'student':'admin',$i%3===0?'s3-student-'.$studentNumber:'stage3-admin@example.invalid',$i%5===0?'student_result_calculated':'assessment_viewed','fixture','s3-course','198.18.0.'.$i%250,'Stage3 load fixture','success','stage3-audit',json_encode([],JSON_THROW_ON_ERROR),$metadata]);}
    $pdo->prepare('INSERT INTO grading_scale_bands (institution_id,ordinal,min_score,max_score,grade,grade_point) VALUES (?,?,?,?,?,?)')->execute([$institutionId,0,0,39.99,'F',0]);$pdo->prepare('INSERT INTO grading_scale_bands (institution_id,ordinal,min_score,max_score,grade,grade_point) VALUES (?,?,?,?,?,?)')->execute([$institutionId,1,40,100,'A',5]);$pdo->prepare("INSERT INTO institution_settings (institution_id,setting_key,setting_json) VALUES (?,'studentPortalSetupMode','false')")->execute([$institutionId]);
    $pdo->prepare('INSERT INTO questions (institution_id,id,course_id,text,type,topic,difficulty,status) VALUES (?,\'s3-q1\',\'s3-course\',\'Stage 3 question\',\'single\',\'Performance\',\'easy\',\'published\')')->execute([$institutionId]);foreach([[0,'Correct',1],[1,'Wrong',0]] as [$index,$text,$correct])$pdo->prepare('INSERT INTO question_options (institution_id,question_id,option_index,option_text,is_correct) VALUES (?,\'s3-q1\',?,?,?)')->execute([$institutionId,$index,$text,$correct]);$pdo->prepare("INSERT INTO question_publish_targets (institution_id,question_id,target_component) VALUES (?, 's3-q1','test')")->execute([$institutionId]);
    $attempt=$pdo->prepare('INSERT INTO assessment_attempts (institution_id,id,student_id,component_id,status,started_at,ends_at,access_token_hash,snapshot_json) VALUES (?,?,?,?,?,?,?,?,?)');$snapshot=$pdo->prepare('INSERT INTO attempt_question_snapshots (institution_id,attempt_id,question_id,ordinal,question_json) VALUES (?, ?,\'s3-q1\',0,?)');$tokenHash=hash('sha256','stage1-burst-token');$question=json_encode(['id'=>'s3-q1','text'=>'Stage 3 question','options'=>['Correct','Wrong'],'originalOptions'=>['Correct','Wrong'],'correctOptions'=>[0],'optionOrder'=>[0,1],'type'=>'single'],JSON_THROW_ON_ERROR);for($i=1;$i<=60;$i++){ $id='burst-attempt-'.$i;$snapshotJson=json_encode(['id'=>$id,'studentId'=>'s3-student-'.$i,'examId'=>'s3-test','accessTokenHash'=>$tokenHash,'startedAt'=>$now->format('c'),'endsAt'=>$now->modify('+30 minutes')->format('c'),'questions'=>[json_decode($question,true,512,JSON_THROW_ON_ERROR)],'answers'=>[],'flagged'=>[],'integrityEvents'=>[],'status'=>'in_progress'],JSON_THROW_ON_ERROR);$attempt->execute([$institutionId,$id,'s3-student-'.$i,'s3-test','in_progress',$created,$now->modify('+30 minutes')->format('Y-m-d H:i:s.u'),$tokenHash,$snapshotJson]);$snapshot->execute([$institutionId,$id,$question]);}
    $security=['optionShuffleEnabled'=>false,'fingerprintFlaggingEnabled'=>false,'concurrentIpBlockEnabled'=>true,'loginRateLimitEnabled'=>true,'loginAttemptLimit'=>5,'loginAttemptWindowMinutes'=>10,'loginLockoutMinutes'=>15,'ipAttemptLimit'=>30,'ipAttemptWindowMinutes'=>1];$pdo->prepare("INSERT INTO institution_settings (institution_id,setting_key,setting_json) VALUES (?,'examSecurity',?)")->execute([$institutionId,json_encode($security,JSON_THROW_ON_ERROR)]);$pdo->commit();echo json_encode(['pass'=>true,'institutionId'=>$institutionId,'slug'=>$slug,'students'=>300,'submissions'=>600,'auditEvents'=>3000],JSON_UNESCAPED_SLASHES).PHP_EOL;
}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
