<?php
declare(strict_types=1);

/** Builds an isolated, disposable tenant for Stage 2 performance verification. */
require_once __DIR__ . DIRECTORY_SEPARATOR . 'mysql_connection.php';

$slug = $argv[1] ?? '';
if (!is_string($slug) || !preg_match('/^perf-stage2-[a-z0-9-]+$/', $slug)) { fwrite(STDERR, "Use a disposable perf-stage2-* slug.\n"); exit(2); }
$root = dirname(__DIR__); $pdo = mysqlMigrationPdo($root);
$exists=$pdo->prepare('SELECT id FROM institutions WHERE slug=:slug');$exists->execute(['slug'=>$slug]);if($exists->fetchColumn())throw new RuntimeException('Fixture slug already exists.');
$now=new DateTimeImmutable('now',new DateTimeZone('UTC'));$created=$now->format('Y-m-d H:i:s.u');$start=$now->modify('-5 minutes')->format('Y-m-d H:i:s.u');$end=$now->modify('+60 minutes')->format('Y-m-d H:i:s.u');
$pdo->beginTransaction();try{
    $pdo->prepare('INSERT INTO institutions (name,slug,active,created_at) VALUES (:name,:slug,1,:created_at)')->execute(['name'=>'Stage 2 Performance Fixture','slug'=>$slug,'created_at'=>$created]);$institutionId=(int)$pdo->lastInsertId();
    $pdo->prepare('INSERT INTO institution_branding (institution_id,display_name,portal_title,logo_path,favicon_path,accent_source_color,primary_color,accent_color,nav_label,assessment_label,footer_primary,footer_secondary,footer_legal,result_sheet_title,newsletter_sender_name,support_email,updated_at) VALUES (:institution_id,:display_name,:portal_title,:logo_path,:favicon_path,:source,:primary,:accent,:nav,:assessment,:footer_primary,:footer_secondary,:footer_legal,:result_title,:sender,:email,:updated_at)')->execute(['institution_id'=>$institutionId,'display_name'=>'Stage 2 Test','portal_title'=>'Stage 2 Test CBT','logo_path'=>'CACSA%20Logo.jpeg','favicon_path'=>'favicon.php','source'=>'#16774d','primary'=>'#16774d','accent'=>'#105839','nav'=>'Stage 2 Test CBT','assessment'=>'Assessment centre','footer_primary'=>'Stage 2 test node','footer_secondary'=>'Disposable test tenant','footer_legal'=>'© {year} Stage 2 Test','result_title'=>'Stage 2 Test CBT','sender'=>'Stage 2 Test','email'=>'stage2@example.invalid','updated_at'=>$created]);
    $pdo->prepare('INSERT INTO academic_sessions (institution_id,id,label,is_active,created_at) VALUES (:institution_id,\'s2-session\',\'2026/2027\',1,:created_at)')->execute(['institution_id'=>$institutionId,'created_at'=>$created]);
    $pdo->prepare('INSERT INTO academic_semesters (institution_id,id,session_id,label,is_active,created_at) VALUES (:institution_id,\'s2-semester\',\'s2-session\',\'Harmattan Semester\',1,:created_at)')->execute(['institution_id'=>$institutionId,'created_at'=>$created]);
    $pdo->prepare('INSERT INTO courses (institution_id,id,session_id,semester_id,code,title,course_unit,test_max_mark,exam_max_mark,legacy_exam_only,created_at) VALUES (:institution_id,\'s2-course\',\'s2-session\',\'s2-semester\',\'S2 101\',\'Performance Testing\',3,30,70,0,:created_at)')->execute(['institution_id'=>$institutionId,'created_at'=>$created]);
    $pdo->prepare('INSERT INTO course_components (institution_id,id,course_id,component,code,title,duration_minutes,max_mark,question_count,start_at,end_at,status,legacy_exam_only,created_at) VALUES (:institution_id,\'s2-test\',\'s2-course\',\'test\',\'S2 101\',\'Performance Testing\',60,30,2,:start_at,:end_at,\'active\',0,:created_at)')->execute(['institution_id'=>$institutionId,'start_at'=>$start,'end_at'=>$end,'created_at'=>$created]);
    $insertStudent=$pdo->prepare('INSERT INTO students (institution_id,id,full_name,matric_number,email,department,active,created_at) VALUES (:institution_id,:id,:name,:matric,:email,\'Testing\',1,:created_at)');
    $insertStudent->execute(['institution_id'=>$institutionId,'id'=>'s2-live-student','name'=>'Stage Two Student','matric'=>'S2/001','email'=>'s2-live@example.invalid','created_at'=>$created]);
    for($i=1;$i<=60;$i++)$insertStudent->execute(['institution_id'=>$institutionId,'id'=>'burst-student-'.$i,'name'=>'Burst Student '.$i,'matric'=>'S2/B'.str_pad((string)$i,3,'0',STR_PAD_LEFT),'email'=>'burst-'.$i.'@example.invalid','created_at'=>$created]);
    $insertQuestion=$pdo->prepare('INSERT INTO questions (institution_id,id,course_id,text,type,topic,difficulty,status) VALUES (:institution_id,:id,\'s2-course\',:text,\'single\',\'Performance\',\'easy\',\'published\')');$insertOption=$pdo->prepare('INSERT INTO question_options (institution_id,question_id,option_index,option_text,is_correct) VALUES (:institution_id,:question_id,:option_index,:option_text,:is_correct)');$insertTarget=$pdo->prepare('INSERT INTO question_publish_targets (institution_id,question_id,target_component) VALUES (:institution_id,:question_id,\'test\')');
    $questions=[];foreach([['s2-q1','Which option is correct?',['Correct','Wrong']],['s2-q2','Choose the first answer.',['First','Second']]] as [$id,$text,$options]){$insertQuestion->execute(['institution_id'=>$institutionId,'id'=>$id,'text'=>$text]);foreach($options as $index=>$option)$insertOption->execute(['institution_id'=>$institutionId,'question_id'=>$id,'option_index'=>$index,'option_text'=>$option,'is_correct'=>$index===0?1:0]);$insertTarget->execute(['institution_id'=>$institutionId,'question_id'=>$id]);$questions[]=['id'=>$id,'text'=>$text,'options'=>$options,'originalOptions'=>$options,'correctOptions'=>[0],'optionOrder'=>[0,1],'type'=>'single'];}
    $password='Stage2!Exam';$hash=password_hash($password,PASSWORD_DEFAULT);$pdo->prepare('INSERT INTO assessment_passwords (institution_id,id,student_id,component_id,password_hash,created_at,expires_at) VALUES (:institution_id,\'s2-password\',\'s2-live-student\',\'s2-test\',:hash,:created_at,:expires_at)')->execute(['institution_id'=>$institutionId,'hash'=>$hash,'created_at'=>$created,'expires_at'=>$end]);
    $insertAttempt=$pdo->prepare('INSERT INTO assessment_attempts (institution_id,id,student_id,component_id,status,started_at,ends_at,access_token_hash,snapshot_json) VALUES (:institution_id,:id,:student_id,\'s2-test\',\'in_progress\',:started_at,:ends_at,:token_hash,:snapshot_json)');$insertSnapshot=$pdo->prepare('INSERT INTO attempt_question_snapshots (institution_id,attempt_id,question_id,ordinal,question_json) VALUES (:institution_id,:attempt_id,\'s2-q1\',0,:question_json)');$tokenHash=hash('sha256','stage2-burst-token');for($i=1;$i<=60;$i++){ $session=['id'=>'burst-attempt-'.$i,'studentId'=>'burst-student-'.$i,'examId'=>'s2-test','accessTokenHash'=>$tokenHash,'startedAt'=>$now->format('c'),'endsAt'=>$now->modify('+30 minutes')->format('c'),'questions'=>[$questions[0]],'answers'=>[],'flagged'=>[],'integrityEvents'=>[],'status'=>'in_progress'];$insertAttempt->execute(['institution_id'=>$institutionId,'id'=>$session['id'],'student_id'=>'burst-student-'.$i,'started_at'=>$created,'ends_at'=>$now->modify('+30 minutes')->format('Y-m-d H:i:s.u'),'token_hash'=>$tokenHash,'snapshot_json'=>json_encode($session,JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)]);$insertSnapshot->execute(['institution_id'=>$institutionId,'attempt_id'=>$session['id'],'question_json'=>json_encode($questions[0],JSON_UNESCAPED_SLASHES|JSON_THROW_ON_ERROR)]);}
    $security=['optionShuffleEnabled'=>false,'fingerprintFlaggingEnabled'=>false,'concurrentIpBlockEnabled'=>true,'loginRateLimitEnabled'=>true,'loginAttemptLimit'=>5,'loginAttemptWindowMinutes'=>10,'loginLockoutMinutes'=>15,'ipAttemptLimit'=>30,'ipAttemptWindowMinutes'=>1];$pdo->prepare("INSERT INTO institution_settings (institution_id,setting_key,setting_json) VALUES (:institution_id,'examSecurity',:setting_json)")->execute(['institution_id'=>$institutionId,'setting_json'=>json_encode($security,JSON_THROW_ON_ERROR)]);
    $pdo->commit();echo json_encode(['pass'=>true,'institutionId'=>$institutionId,'slug'=>$slug,'studentMatric'=>'S2/001','studentPassword'=>$password,'componentId'=>'s2-test'],JSON_UNESCAPED_SLASHES).PHP_EOL;
}catch(Throwable $error){if($pdo->inTransaction())$pdo->rollBack();throw $error;}
