<?php
declare(strict_types=1);

require __DIR__ . DIRECTORY_SEPARATOR . 'mysql_connection.php';

const VERIFY_INSTITUTION_ID = 1;

function canonicalize(mixed $value): mixed {
    if (!is_array($value)) return $value;
    if (array_is_list($value)) return array_map('canonicalize', $value);
    ksort($value);
    foreach ($value as $key => $item) $value[$key] = canonicalize($item);
    return $value;
}
function semanticHash(mixed $value): string { return hash('sha256', json_encode(canonicalize($value), JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE | JSON_PRESERVE_ZERO_FRACTION | JSON_THROW_ON_ERROR)); }
function sourceCount(array $data, string $key): int { return isset($data[$key]) && is_array($data[$key]) ? count($data[$key]) : 0; }
function dbCount(PDO $pdo, string $table): int {
    static $sql = [
        'academic_sessions'=>'SELECT COUNT(*) FROM academic_sessions WHERE institution_id=:institution_id','academic_semesters'=>'SELECT COUNT(*) FROM academic_semesters WHERE institution_id=:institution_id','courses'=>'SELECT COUNT(*) FROM courses WHERE institution_id=:institution_id','course_components'=>'SELECT COUNT(*) FROM course_components WHERE institution_id=:institution_id','students'=>'SELECT COUNT(*) FROM students WHERE institution_id=:institution_id','questions'=>'SELECT COUNT(*) FROM questions WHERE institution_id=:institution_id','assessment_passwords'=>'SELECT COUNT(*) FROM assessment_passwords WHERE institution_id=:institution_id','assessment_login_tokens'=>'SELECT COUNT(*) FROM assessment_login_tokens WHERE institution_id=:institution_id','assessment_attempts'=>'SELECT COUNT(*) FROM assessment_attempts WHERE institution_id=:institution_id','component_submissions'=>'SELECT COUNT(*) FROM component_submissions WHERE institution_id=:institution_id','calculated_results'=>'SELECT COUNT(*) FROM calculated_results WHERE institution_id=:institution_id','roles'=>'SELECT COUNT(*) FROM roles WHERE institution_id=:institution_id','admin_users'=>'SELECT COUNT(*) FROM admin_users WHERE institution_id=:institution_id','admin_sessions'=>'SELECT COUNT(*) FROM admin_sessions WHERE institution_id=:institution_id','pending_admin_requests'=>'SELECT COUNT(*) FROM pending_admin_requests WHERE institution_id=:institution_id','admin_email_verifications'=>'SELECT COUNT(*) FROM admin_email_verifications WHERE institution_id=:institution_id','admin_password_resets'=>'SELECT COUNT(*) FROM admin_password_resets WHERE institution_id=:institution_id','admin_two_factor_challenges'=>'SELECT COUNT(*) FROM admin_two_factor_challenges WHERE institution_id=:institution_id','emergency_recovery_codes'=>'SELECT COUNT(*) FROM emergency_recovery_codes WHERE institution_id=:institution_id','audit_events'=>'SELECT COUNT(*) FROM audit_events WHERE institution_id=:institution_id','rate_limit_records'=>'SELECT COUNT(*) FROM rate_limit_records WHERE institution_id=:institution_id','exam_login_failures'=>'SELECT COUNT(*) FROM exam_login_failures WHERE institution_id=:institution_id','exam_login_ip_attempts'=>'SELECT COUNT(*) FROM exam_login_ip_attempts WHERE institution_id=:institution_id','exam_flags'=>'SELECT COUNT(*) FROM exam_flags WHERE institution_id=:institution_id','newsletter_subscribers'=>'SELECT COUNT(*) FROM newsletter_subscribers WHERE institution_id=:institution_id','newsletters'=>'SELECT COUNT(*) FROM newsletters WHERE institution_id=:institution_id','admin_profile_overrides'=>'SELECT COUNT(*) FROM admin_profile_overrides WHERE institution_id=:institution_id','admin_user_activity'=>'SELECT COUNT(*) FROM admin_user_activity WHERE institution_id=:institution_id','dashboard_hidden_outcomes'=>'SELECT COUNT(*) FROM dashboard_hidden_outcomes WHERE institution_id=:institution_id',
    ];
    $statement = $pdo->prepare($sql[$table]); $statement->execute(['institution_id'=>VERIFY_INSTITUTION_ID]); return (int)$statement->fetchColumn();
}
function gradePoint(float $score, array $bands): float { foreach($bands as $band) if($score >= (float)$band['min_score'] && $score <= (float)$band['max_score']) return (float)$band['grade_point']; return 0.0; }

$root = dirname(__DIR__); $raw = file_get_contents($root . DIRECTORY_SEPARATOR . 'cbt-data.json');
if ($raw === false) throw new RuntimeException('Legacy JSON could not be read.');
$data = json_decode($raw, true, 512, JSON_THROW_ON_ERROR); $sourceHash = hash('sha256',$raw); $pdo = mysqlMigrationPdo($root);
$migration = $pdo->prepare('SELECT status,source_sha256 FROM storage_migrations WHERE institution_id=:institution_id AND migration_key=:migration_key'); $migration->execute(['institution_id'=>1,'migration_key'=>'json_to_mysql_phase_1']); $migrationRow=$migration->fetch();

$mapping = ['academicSessions'=>'academic_sessions','semesters'=>'academic_semesters','courses'=>'courses','exams'=>'course_components','students'=>'students','questions'=>'questions','passwords'=>'assessment_passwords','loginTokens'=>'assessment_login_tokens','sessions'=>'assessment_attempts','results'=>'component_submissions','calculatedResults'=>'calculated_results','roles'=>'roles','adminUsers'=>'admin_users','adminSessions'=>'admin_sessions','pendingAdminRequests'=>'pending_admin_requests','adminEmailVerifications'=>'admin_email_verifications','adminPasswordResets'=>'admin_password_resets','admin2faChallenges'=>'admin_two_factor_challenges','rateLimits'=>'rate_limit_records','examLoginFailures'=>'exam_login_failures','examLoginIpAttempts'=>'exam_login_ip_attempts','examFlags'=>'exam_flags','newsletterSubscribers'=>'newsletter_subscribers','newsletters'=>'newsletters','adminProfileOverrides'=>'admin_profile_overrides','adminUserActivity'=>'admin_user_activity','dashboardHiddenOutcomes'=>'dashboard_hidden_outcomes'];
$counts=[]; foreach($mapping as $jsonEntity=>$table){$expected=sourceCount($data,$jsonEntity); if($jsonEntity==='emergencyRecoveryCodes')$expected=count($data['emergencyRecoveryCodes']['codes']??[]); $actual=dbCount($pdo,$table); $counts[$jsonEntity]=['json'=>$expected,'mysql'=>$actual,'match'=>$expected===$actual];}
$emergencyExpected=count($data['emergencyRecoveryCodes']['codes']??[]);$emergencyActual=dbCount($pdo,'emergency_recovery_codes');$counts['emergencyRecoveryCodes']=['json'=>$emergencyExpected,'mysql'=>$emergencyActual,'match'=>$emergencyExpected===$emergencyActual];
$auditActual=dbCount($pdo,'audit_events');$counts['auditEvents']=['json'=>sourceCount($data,'auditEvents'),'mysqlSourceRows'=>max(0,$auditActual-1),'mysqlIncludingMigrationPreparation'=>$auditActual,'match'=>sourceCount($data,'auditEvents')===max(0,$auditActual-1)];

$orphanSql = [
  'components_without_course'=>'SELECT COUNT(*) FROM course_components x LEFT JOIN courses p ON p.institution_id=x.institution_id AND p.id=x.course_id WHERE x.institution_id=1 AND p.id IS NULL',
  'questions_without_course'=>'SELECT COUNT(*) FROM questions x LEFT JOIN courses p ON p.institution_id=x.institution_id AND p.id=x.course_id WHERE x.institution_id=1 AND p.id IS NULL',
  'attempts_without_student'=>'SELECT COUNT(*) FROM assessment_attempts x LEFT JOIN students p ON p.institution_id=x.institution_id AND p.id=x.student_id WHERE x.institution_id=1 AND p.id IS NULL',
  'attempts_without_component'=>'SELECT COUNT(*) FROM assessment_attempts x LEFT JOIN course_components p ON p.institution_id=x.institution_id AND p.id=x.component_id WHERE x.institution_id=1 AND p.id IS NULL',
  'submissions_without_attempt'=>'SELECT COUNT(*) FROM component_submissions x LEFT JOIN assessment_attempts p ON p.institution_id=x.institution_id AND p.id=x.attempt_id WHERE x.institution_id=1 AND x.attempt_id IS NOT NULL AND p.id IS NULL',
  'submissions_without_student'=>'SELECT COUNT(*) FROM component_submissions x LEFT JOIN students p ON p.institution_id=x.institution_id AND p.id=x.student_id WHERE x.institution_id=1 AND p.id IS NULL',
  'calculated_without_student'=>'SELECT COUNT(*) FROM calculated_results x LEFT JOIN students p ON p.institution_id=x.institution_id AND p.id=x.student_id WHERE x.institution_id=1 AND p.id IS NULL',
];
$relationships=[]; foreach($orphanSql as $label=>$sql)$relationships[$label]=(int)$pdo->query($sql)->fetchColumn(); $relationships['allClear']=array_sum($relationships)===0;

$attemptRows=$pdo->prepare('SELECT id,snapshot_json FROM assessment_attempts WHERE institution_id=:institution_id');$attemptRows->execute(['institution_id'=>1]);$attemptDb=[];foreach($attemptRows as $row)$attemptDb[$row['id']]=json_decode($row['snapshot_json'],true,512,JSON_THROW_ON_ERROR);$attemptHashes=[];foreach($data['sessions']??[] as $session){$id=(string)$session['id'];$match=isset($attemptDb[$id])&&semanticHash($session)===semanticHash($attemptDb[$id]);$attemptHashes[$id]=$match;}
$submissionRows=$pdo->prepare('SELECT id,review_snapshot_json FROM component_submissions WHERE institution_id=:institution_id');$submissionRows->execute(['institution_id'=>1]);$submissionDb=[];foreach($submissionRows as $row)$submissionDb[$row['id']]=json_decode($row['review_snapshot_json'],true,512,JSON_THROW_ON_ERROR);$submissionHashes=[];foreach($data['results']??[] as $result){$id=(string)$result['id'];$expected=['questions'=>$result['questions']??[],'integrityEvents'=>$result['integrityEvents']??[]];$submissionHashes[$id]=isset($submissionDb[$id])&&semanticHash($expected)===semanticHash($submissionDb[$id]);}
$snapshots=['attempts'=>['expected'=>count($data['sessions']??[]),'checked'=>count($attemptHashes),'matched'=>count(array_filter($attemptHashes)),'allMatch'=>count($attemptHashes)===count($data['sessions']??[])&&!in_array(false,$attemptHashes,true)],'submissions'=>['expected'=>count($data['results']??[]),'checked'=>count($submissionHashes),'matched'=>count(array_filter($submissionHashes)),'allMatch'=>count($submissionHashes)===count($data['results']??[])&&!in_array(false,$submissionHashes,true)]];

$bands=$pdo->query('SELECT min_score,max_score,grade_point FROM grading_scale_bands WHERE institution_id=1 ORDER BY ordinal')->fetchAll();$courses=$pdo->query('SELECT id,session_id,semester_id,course_unit,test_max_mark,exam_max_mark FROM courses WHERE institution_id=1')->fetchAll();$submissions=$pdo->query('SELECT student_id,course_id,component,scaled_score,score,submitted_at,id FROM component_submissions WHERE institution_id=1 ORDER BY submitted_at,id')->fetchAll();$gpaChecks=[];
foreach($data['calculatedResults']??[] as $saved){$student=(string)$saved['studentId'];$latest=[];foreach($submissions as $submission){if($submission['student_id']!==$student)continue;$key=$submission['course_id'].'|'.$submission['component'];$latest[$key]=$submission;} $totalUnits=0;$totalQuality=0;$periodUnits=0;$periodQuality=0;foreach($courses as $course){$test=$latest[$course['id'].'|test']??null;$exam=$latest[$course['id'].'|exam']??null;$testMax=(float)$course['test_max_mark'];$examMax=(float)$course['exam_max_mark'];$complete=($testMax<=0||$test!==null)&&($examMax<=0||$exam!==null)&&($testMax+$examMax>0);if(!$complete)continue;$score=(float)($test['scaled_score']??$test['score']??0)+(float)($exam['scaled_score']??$exam['score']??0);$unit=max(1,(int)$course['course_unit']);$quality=$unit*gradePoint($score,$bands);$totalUnits+=$unit;$totalQuality+=$quality;if($course['session_id']===$saved['sessionId']&&$course['semester_id']===$saved['semesterId']){$periodUnits+=$unit;$periodQuality+=$quality;}}$semester=round($periodUnits?$periodQuality/$periodUnits:0,2);$cgpa=round($totalUnits?$totalQuality/$totalUnits:0,2);$gpaChecks[(string)$saved['id']]=['expectedSemesterGpa'=>(float)$saved['semesterGpa'],'recomputedSemesterGpa'=>$semester,'expectedCgpa'=>(float)$saved['cgpa'],'recomputedCgpa'=>$cgpa,'match'=>abs((float)$saved['semesterGpa']-$semester)<0.00001&&abs((float)$saved['cgpa']-$cgpa)<0.00001];}

echo json_encode(['migration'=>['status'=>$migrationRow['status']??null,'sourceHashMatches'=>isset($migrationRow['source_sha256'])&&hash_equals($migrationRow['source_sha256'],$sourceHash)],'counts'=>$counts,'relationships'=>$relationships,'gpaCgpa'=>$gpaChecks,'snapshotHashes'=>$snapshots],JSON_UNESCAPED_SLASHES|JSON_PRETTY_PRINT).PHP_EOL;
