<?php
declare(strict_types=1);

/* Disposable Stage 2 verification.  It uses the deployed tenant URL, proves
 * ID-guess isolation, exercises each read/draft capability, then removes only
 * the disposable tenant after leaving a local safety manifest. */
require_once __DIR__ . DIRECTORY_SEPARATOR . 'mysql_connection.php';

$root = dirname(__DIR__); $pdo = mysqlMigrationPdo($root); $id = 0;
$slug='algebra-stage2-test-'.gmdate('Ymdhis'); $token=bin2hex(random_bytes(32));
$base='http://localhost/BEREVION/i/'.rawurlencode($slug).'/api.php?action=';
$tracked=['students','courses','questions','question_options','question_publish_targets','assessment_attempts','component_submissions','audit_events','calculated_results'];
$hash=static function(PDO $db,string $table):string{$q=$db->query("SELECT * FROM {$table} WHERE institution_id=1 ORDER BY 1");return hash('sha256',json_encode($q->fetchAll(),JSON_UNESCAPED_SLASHES));};$before=[];foreach($tracked as $table)$before[$table]=$hash($pdo,$table);
function algebra2Csrf(string $url,string $token):string{$c=stream_context_create(['http'=>['method'=>'GET','header'=>"Accept: application/json\r\nCookie: CBT_ADMIN_SESSION={$token}",'ignore_errors'=>true,'timeout'=>30]]);$raw=file_get_contents($url,false,$c);$token=(string)((json_decode((string)$raw,true)['csrfToken']??''));if($token==='')throw new RuntimeException('Stage 2 CSRF request failed.');return $token;}
function algebra2Http(string $url,string $token,array $payload):array{static $csrfByToken=[];$csrf=$csrfByToken[$token]??null;if(!$csrf){$csrf=algebra2Csrf(dirname($url).'/api.php?action=auth-csrf',$token);$csrfByToken[$token]=$csrf;}$headers=['Accept: application/json','Content-Type: application/json','Cookie: CBT_ADMIN_SESSION='.$token.'; CBT_CSRF='.$csrf,'X-CSRF-Token: '.$csrf];$c=stream_context_create(['http'=>['method'=>'POST','header'=>implode("\r\n",$headers),'content'=>json_encode($payload,JSON_UNESCAPED_SLASHES),'ignore_errors'=>true,'timeout'=>180]]);$raw=file_get_contents($url,false,$c);$responseHeaders=$http_response_header??[];preg_match('/\s(\d{3})\s/',$responseHeaders[0]??'',$m);return ['status'=>(int)($m[1]??0),'headers'=>$responseHeaders,'body'=>json_decode((string)$raw,true)?:[]];}
function algebra2Cleanup(PDO $pdo,int $id,string $slug,string $root):void{if($id<1)return;$dir=$root.DIRECTORY_SEPARATOR.'database'.DIRECTORY_SEPARATOR.'backups'.DIRECTORY_SEPARATOR.'institution-'.$id;if(!is_dir($dir))mkdir($dir,0700,true);file_put_contents($dir.DIRECTORY_SEPARATOR.'algebra-stage2-test-safety-'.gmdate('Ymd-His').'.json',json_encode(['kind'=>'algebra-stage2-disposable-cleanup','institutionId'=>$id,'slug'=>$slug,'reason'=>'Stage 2 Algebra verification completed','createdAt'=>gmdate('c')],JSON_PRETTY_PRINT),LOCK_EX);$pdo->beginTransaction();try{foreach(['rate_limit_records','algebra_requests','audit_events','attempt_answers','attempt_question_snapshots','assessment_attempts','calculated_result_items','calculated_results','component_submissions','course_components','courses','students','academic_semesters','academic_sessions','admin_sessions','admin_users','role_permissions','roles','institution_branding'] as $table)$pdo->prepare("DELETE FROM {$table} WHERE institution_id=?")->execute([$id]);$pdo->prepare('DELETE FROM institutions WHERE id=? AND slug=?')->execute([$id,$slug]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}}
try {
  $pdo->beginTransaction();
  $pdo->prepare('INSERT INTO institutions (name,slug,active,created_at) VALUES (?,?,1,UTC_TIMESTAMP(6))')->execute(['Algebra Stage 2 Test',$slug]);$id=(int)$pdo->lastInsertId();
  $pdo->prepare("INSERT INTO institution_branding (institution_id,display_name,portal_title,logo_path,favicon_path,accent_source_color,primary_color,accent_color,nav_label,assessment_label,footer_primary,footer_secondary,footer_legal,result_sheet_title,newsletter_sender_name,support_email,updated_at) VALUES (?,'Algebra Stage 2 Test','Algebra Stage 2 Test','CACSA%20Logo.jpeg','favicon.php','#16774d','#16774d','#105839','Algebra Stage 2 Test','Assessment centre','Disposable test','Algebra verification','© test','Algebra Stage 2 Test','Algebra Test','algebra-test@example.invalid',UTC_TIMESTAMP(6))")->execute([$id]);
  $pdo->prepare("INSERT INTO roles (institution_id,id,name,description,max_users,system_locked) VALUES (?,'admin','Admin','Disposable administrator',2,1)")->execute([$id]);foreach(['questions','results','exams','audit','newsletter'] as $permission)$pdo->prepare("INSERT INTO role_permissions (institution_id,role_id,permission) VALUES (?,'admin',?)")->execute([$id,$permission]);
  $pdo->prepare("INSERT INTO admin_users (institution_id,id,role_id,name,email,password_hash,active,verified,must_change_password,created_at) VALUES (?,'algebra-admin','admin','Algebra Test Admin','algebra-admin@example.invalid','not-used',1,1,0,UTC_TIMESTAMP(6))")->execute([$id]);$pdo->prepare("INSERT INTO admin_sessions (institution_id,token_hash,user_id,email,name,role_id,permissions_json,correlation_id,created_at,last_seen_at,expires_at) VALUES (?,?, 'algebra-admin','algebra-admin@example.invalid','Algebra Test Admin','admin','[\"questions\",\"results\",\"exams\",\"audit\",\"newsletter\"]','algebra-stage2-test',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),'2099-12-31 23:59:59.000000')")->execute([$id,hash('sha256',$token)]);
  $pdo->prepare("INSERT INTO academic_sessions (institution_id,id,label,is_active,created_at) VALUES (?,'s1','2026/2027',1,UTC_TIMESTAMP(6))")->execute([$id]);$pdo->prepare("INSERT INTO academic_semesters (institution_id,id,session_id,label,start_date,end_date,is_active,created_at) VALUES (?,'sem1','s1','Harmattan Semester','2026-01-01','2026-05-01',1,UTC_TIMESTAMP(6))")->execute([$id]);
  $pdo->prepare("INSERT INTO courses (institution_id,id,session_id,semester_id,code,title,course_unit,test_max_mark,exam_max_mark,legacy_exam_only,created_at) VALUES (?,'c1','s1','sem1','ALG 201','Stage 2 Algebra',3,30,70,0,UTC_TIMESTAMP(6))")->execute([$id]);$pdo->prepare("INSERT INTO course_components (institution_id,id,course_id,component,code,title,duration_minutes,max_mark,pass_threshold,question_count,status,created_at) VALUES (?,'cmp1','c1','exam','ALG 201','Stage 2 Algebra',60,70,35,10,'draft',UTC_TIMESTAMP(6))")->execute([$id]);
  $pdo->prepare("INSERT INTO students (institution_id,id,full_name,matric_number,email,department,active,created_at) VALUES (?,'student1','Test Student','ALG/001','student@example.invalid','Testing',1,UTC_TIMESTAMP(6))")->execute([$id]);$pdo->prepare("INSERT INTO calculated_results (institution_id,id,student_id,session_id,semester_id,source_hash,semester_gpa,cgpa,calculated_at) VALUES (?,'cr1','student1','s1','sem1',REPEAT('a',64),4.0,4.0,UTC_TIMESTAMP(6))")->execute([$id]);$pdo->prepare("INSERT INTO calculated_result_items (institution_id,calculated_result_id,course_id,item_json) VALUES (?,'cr1','c1',?)")->execute([$id,json_encode(['courseCode'=>'ALG 201','courseTitle'=>'Stage 2 Algebra','score'=>80,'grade'=>'A','gradePoint'=>5,'qualityPoints'=>15])]);
  $q=['id'=>'q1','text'=>'What is 2 + 2?','options'=>['3','4','5','6'],'correctOptions'=>[1],'type'=>'single'];for($i=1;$i<=10;$i++){$attempt='a'.$i;$pdo->prepare("INSERT INTO assessment_attempts (institution_id,id,student_id,component_id,status,snapshot_json) VALUES (? ,?,'student1','cmp1','submitted','{}')")->execute([$id,$attempt]);$pdo->prepare("INSERT INTO attempt_question_snapshots (institution_id,attempt_id,question_id,ordinal,question_json) VALUES (? ,?,'q1',1,?)")->execute([$id,$attempt,json_encode($q)]);$pdo->prepare("INSERT INTO attempt_answers (institution_id,attempt_id,question_id,option_index) VALUES (? ,?,'q1',0)")->execute([$id,$attempt]);}
  $pdo->prepare("INSERT INTO audit_events (institution_id,id,timestamp_at,actor_type,actor_id,action_type,target_type,target_id,outcome,metadata_json) VALUES (?,'audit1',UTC_TIMESTAMP(6),'admin','algebra-admin','course_updated','course','c1','success','{}')")->execute([$id]);$pdo->commit();$pdo->prepare('DELETE FROM rate_limit_records WHERE institution_id=?')->execute([$id]);
  $cacsaStudent=(string)$pdo->query('SELECT id FROM students WHERE institution_id=1 ORDER BY id LIMIT 1')->fetchColumn();$cross=algebra2Http($base.'algebra-result-report',$token,['studentId'=>$cacsaStudent,'sessionId'=>'s1','semesterId'=>'sem1']);$pdo->prepare('DELETE FROM rate_limit_records WHERE institution_id=?')->execute([$id]);$missing=algebra2Http($base.'algebra-result-report',$token,['studentId'=>'missing-student','sessionId'=>'missing-session','semesterId'=>'missing-semester']);if($cross['status']!==404||$missing['status']!==404||json_encode($cross['headers'],JSON_UNESCAPED_SLASHES)!==json_encode($missing['headers'],JSON_UNESCAPED_SLASHES)||json_encode($cross['body'],JSON_UNESCAPED_SLASHES)!==json_encode($missing['body'],JSON_UNESCAPED_SLASHES))throw new RuntimeException('Cross-tenant and nonexistent result probes were not byte-identical 404 responses: '.json_encode(['cross'=>$cross,'missing'=>$missing]));
  $setup=algebra2Http($base.'algebra-setup-suggestion',$token,['formType'=>'course','brief'=>'Create an introductory algebra course with a short test and final examination.']);if($setup['status']!==200||empty($setup['body']['fields']))throw new RuntimeException('Setup suggestion failed: '.json_encode($setup));
  $digest=algebra2Http($base.'algebra-audit-digest',$token,['from'=>'2026-01-01','to'=>'2026-12-31']);if($digest['status']!==200||empty($digest['body']['summary']))throw new RuntimeException('Audit digest failed: '.json_encode($digest));
  $anomaly=algebra2Http($base.'algebra-anomaly-flags',$token,[]);if($anomaly['status']!==200||empty($anomaly['body']['reviewRecommended'])||empty($anomaly['body']['flags']))throw new RuntimeException('Anomaly flag flow failed: '.json_encode($anomaly));
  $communication=algebra2Http($base.'algebra-communication-draft',$token,['purpose'=>'assessment reminder','audience'=>'registered students','keyPoints'=>'Bring your matriculation number. Arrive fifteen minutes early.']);if($communication['status']!==200||empty($communication['body']['subject'])||empty($communication['body']['sendRequired']))throw new RuntimeException('Communication draft failed: '.json_encode($communication));
  $report=algebra2Http($base.'algebra-result-report',$token,['studentId'=>'student1','sessionId'=>'s1','semesterId'=>'sem1']);if($report['status']!==200||empty($report['body']['summary'])||empty($report['body']['draftOnly']))throw new RuntimeException('Result report draft failed: '.json_encode($report));
  $writes=$pdo->prepare("SELECT capability,response_json FROM algebra_requests WHERE institution_id=? ORDER BY created_at");$writes->execute([$id]);foreach($writes->fetchAll() as $row){$payload=(string)$row['response_json'];if(in_array($row['capability'],['setup_suggestion','audit_digest','anomaly_review','communication_draft','result_report'],true)&&$payload==='')throw new RuntimeException('Missing Stage 2 request ledger response.');}foreach($before as $table=>$value)if(!hash_equals($value,$hash($pdo,$table)))throw new RuntimeException("CACSA {$table} changed during Stage 2 verification.");
  $result=['pass'=>true,'tenantSlug'=>$slug,'crossTenantResultIdGuess'=>'blocked-422','setup'=>'suggestion-only','auditDigest'=>'aggregate-only','anomalyFlags'=>'review-only-no-student-action','communication'=>'draft-only-no-send','resultReport'=>'draft-only-no-grade-change','cacsaHashes'=>'unchanged'];
} finally {if($pdo->inTransaction())$pdo->rollBack();algebra2Cleanup($pdo,$id,$slug,$root);}
echo json_encode($result??['pass'=>false],JSON_UNESCAPED_SLASHES).PHP_EOL;
