<?php
declare(strict_types=1);

/** Full disposable API/worker queue verification. No external provider is called. */
require_once __DIR__ . DIRECTORY_SEPARATOR . 'mysql_connection.php';

$root = dirname(__DIR__); $pdo = mysqlMigrationPdo($root); $slug = 'pdf-queue-test-' . gmdate('Ymdhis'); $institutionId = 0; $token = bin2hex(random_bytes(32)); $courseId = 'pdf-queue-course';
$tracked = ['students','courses','questions','component_submissions','audit_events','pdf_import_jobs'];
$hash = static function (PDO $db, string $table): string { $s=$db->query("SELECT * FROM {$table} WHERE institution_id=1 ORDER BY 1"); return hash('sha256', json_encode($s->fetchAll(), JSON_UNESCAPED_SLASHES)); };
$before=[]; foreach($tracked as $table) $before[$table]=$hash($pdo,$table);
function queueHttp(string $url, string $token, string $method='GET', ?string $body=null, array $extra=[]): array {
    $hasCookie=false; foreach($extra as $header) if(str_starts_with(strtolower($header),'cookie:'))$hasCookie=true; $headers=array_merge(['Accept: application/json'], $hasCookie ? [] : ['Cookie: CBT_ADMIN_SESSION='.$token], $extra); $context=stream_context_create(['http'=>['method'=>$method,'header'=>implode("\r\n",$headers),'content'=>$body ?? '','ignore_errors'=>true,'timeout'=>30]]); $raw=file_get_contents($url,false,$context); preg_match('/\s(\d{3})\s/',$http_response_header[0]??'',$match); return ['status'=>(int)($match[1]??0),'body'=>json_decode((string)$raw,true)?:[]];
}
function queueCsrf(string $base,string $token): string { $response=queueHttp($base.'?action=auth-csrf',$token); $csrf=(string)($response['body']['csrfToken']??''); if($response['status']!==200||$csrf==='') throw new RuntimeException('Could not establish a disposable queue CSRF session.'); return $csrf; }
function queueMultipart(string $base,string $token,string $csrf,string $courseId,string $path): array { $boundary='----CBTQueue'.bin2hex(random_bytes(8)); $content=file_get_contents($path); $body="--{$boundary}\r\nContent-Disposition: form-data; name=\"courseId\"\r\n\r\n{$courseId}\r\n--{$boundary}\r\nContent-Disposition: form-data; name=\"provider\"\r\n\r\ngemini\r\n--{$boundary}\r\nContent-Disposition: form-data; name=\"pdf\"; filename=\"queue-test.pdf\"\r\nContent-Type: application/pdf\r\n\r\n{$content}\r\n--{$boundary}--\r\n"; return queueHttp($base.'?action=pdf-import-jobs',$token,'POST',$body,['Cookie: CBT_ADMIN_SESSION='.$token.'; CBT_CSRF='.$csrf,'X-CSRF-Token: '.$csrf,'Content-Type: multipart/form-data; boundary='.$boundary]); }
$source=''; $result=[];
try {
    $pdo->beginTransaction();
    $pdo->prepare('INSERT INTO institutions (name,slug,active,created_at) VALUES (:name,:slug,1,UTC_TIMESTAMP(6))')->execute(['name'=>'PDF Queue Test','slug'=>$slug]); $institutionId=(int)$pdo->lastInsertId();
    $pdo->prepare("INSERT INTO institution_branding (institution_id,display_name,portal_title,logo_path,favicon_path,accent_source_color,primary_color,accent_color,nav_label,assessment_label,footer_primary,footer_secondary,footer_legal,result_sheet_title,newsletter_sender_name,support_email,updated_at) VALUES (:id,'PDF Queue Test','PDF Queue Test CBT','CACSA%20Logo.jpeg','favicon.php','#16774d','#16774d','#105839','PDF Queue Test CBT','Assessment centre','Disposable','Test','© test','PDF Queue Test CBT','PDF Queue Test','pdf-queue@example.invalid',UTC_TIMESTAMP(6))")->execute(['id'=>$institutionId]);
    $pdo->prepare("INSERT INTO roles (institution_id,id,name,description,max_users,system_locked) VALUES (:id,'admin','Admin','Disposable queue test',1,1)")->execute(['id'=>$institutionId]); foreach(['questions'] as $permission) $pdo->prepare('INSERT INTO role_permissions (institution_id,role_id,permission) VALUES (:id,\'admin\',:permission)')->execute(['id'=>$institutionId,'permission'=>$permission]);
    $pdo->prepare("INSERT INTO admin_users (institution_id,id,role_id,name,email,password_hash,active,verified,must_change_password,created_at) VALUES (:id,'queue-admin','admin','Queue Admin','pdf-queue@example.invalid','not-used',1,1,0,UTC_TIMESTAMP(6))")->execute(['id'=>$institutionId]);
    $pdo->prepare("INSERT INTO admin_sessions (institution_id,token_hash,user_id,email,name,role_id,permissions_json,correlation_id,created_at,last_seen_at,expires_at) VALUES (:id,:token_hash,'queue-admin','pdf-queue@example.invalid','Queue Admin','admin','[\"questions\"]','pdf-queue-test',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),'2099-12-31 23:59:59.000000')")->execute(['id'=>$institutionId,'token_hash'=>hash('sha256',$token)]);
    $pdo->prepare("INSERT INTO courses (institution_id,id,code,title,course_unit,test_max_mark,exam_max_mark,legacy_exam_only,created_at) VALUES (:id,:course_id,'QST 101','Queued Import Testing',3,0,100,0,UTC_TIMESTAMP(6))")->execute(['id'=>$institutionId,'course_id'=>$courseId]); $pdo->commit();
    $source=$root.DIRECTORY_SEPARATOR.'queue-test-source.pdf'; file_put_contents($source,'%PDF-1.4\nqueue test source\n%%EOF',LOCK_EX);
    $base='http://localhost/BEREVION/i/'.rawurlencode($slug).'/api.php'; $csrf=queueCsrf($base,$token); $queued=queueMultipart($base,$token,$csrf,$courseId,$source);
    if($queued['status']!==202||empty($queued['body']['job']['id'])) throw new RuntimeException('Upload did not return queued job: '.json_encode($queued)); $jobId=(string)$queued['body']['job']['id'];
    $beforeWorker=queueHttp($base.'?action=pdf-import-jobs&id='.$jobId,$token); if(($beforeWorker['body']['job']['status']??'')!=='queued') throw new RuntimeException('Uploaded PDF was not persisted as queued.');
    putenv('CBT_APP_ENV=testing'); putenv('CBT_PDF_IMPORT_TEST_MODE=review_ready'); $worker=shell_exec('"'.PHP_BINARY.'" "'.$root.DIRECTORY_SEPARATOR.'scripts'.DIRECTORY_SEPARATOR.'work_pdf_import_jobs.php"'); putenv('CBT_PDF_IMPORT_TEST_MODE'); putenv('CBT_APP_ENV'); $workerPayload=json_decode((string)$worker,true);
    if(($workerPayload['status']??'')!=='review_ready') throw new RuntimeException('Worker did not move job to review_ready: '.$worker);
    $ready=queueHttp($base.'?action=pdf-import-jobs&id='.$jobId,$token); $job=$ready['body']['job']??[]; if(($job['status']??'')!=='review_ready'||count($job['items']??[])!==2||(int)($job['lowConfidence']??0)!==1) throw new RuntimeException('Review-ready job did not preserve parsed low-confidence items.');
    $reviewItems=$job['items']; $reviewItems[0]['questionText']='Edited review question from administrator'; $importBody=json_encode(['jobId'=>$jobId,'items'=>[$reviewItems[0]]],JSON_UNESCAPED_SLASHES); $csrf=queueCsrf($base,$token); $import=queueHttp($base.'?action=pdf-import-job-import',$token,'POST',$importBody,['Cookie: CBT_ADMIN_SESSION='.$token.'; CBT_CSRF='.$csrf,'X-CSRF-Token: '.$csrf,'Content-Type: application/json']);
    if($import['status']!==201||(int)($import['body']['added']??0)!==1||(string)($import['body']['status']??'')!=='draft') throw new RuntimeException('Reviewed Draft import failed: '.json_encode($import));
    $question=$pdo->prepare('SELECT q.status,COUNT(t.question_id) targets FROM questions q LEFT JOIN question_publish_targets t ON t.institution_id=q.institution_id AND t.question_id=q.id WHERE q.institution_id=:id AND q.course_id=:course_id GROUP BY q.id,q.status'); $question->execute(['id'=>$institutionId,'course_id'=>$courseId]); $question=$question->fetch(); if(($question['status']??'')!=='draft'||(int)($question['targets']??-1)!==0) throw new RuntimeException('Queue import created a published or targeted question.');
    $completed=$pdo->prepare('SELECT status,source_expires_at FROM pdf_import_jobs WHERE institution_id=:id AND id=:job'); $completed->execute(['id'=>$institutionId,'job'=>$jobId]); $completed=$completed->fetch(); if(($completed['status']??'')!=='completed'||empty($completed['source_expires_at'])) throw new RuntimeException('Completed queue job did not schedule source cleanup.');
    // Limit safeguard: a second disposable queued job is deliberately failed by the worker's test-only page-limit path.
    $limitId=bin2hex(random_bytes(16)); $key='uploads/pdf-imports/institution-'.$institutionId.'/'.$limitId.'.pdf'; $dir=$root.DIRECTORY_SEPARATOR.'uploads'.DIRECTORY_SEPARATOR.'pdf-imports'.DIRECTORY_SEPARATOR.'institution-'.$institutionId; if(!is_dir($dir)) mkdir($dir,0700,true); $limitPath=$dir.DIRECTORY_SEPARATOR.$limitId.'.pdf'; file_put_contents($limitPath,'%PDF-1.4\nlimit test\n%%EOF',LOCK_EX); $pdo->prepare("INSERT INTO institution_assets (institution_id,asset_type,storage_key,sha256,size_bytes,mime_type,asset_state,created_at,referenced_at) VALUES (:id,'pdf_import_source',:key,:hash,:size,'application/pdf','active',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))")->execute(['id'=>$institutionId,'key'=>$key,'hash'=>hash_file('sha256',$limitPath),'size'=>filesize($limitPath)]); $pdo->prepare("INSERT INTO pdf_import_jobs (institution_id,id,course_id,requested_by_admin_id,requested_by_email,provider,status,source_key,source_filename,source_sha256,source_size_bytes,available_at,created_at,updated_at) VALUES (:institution_id,:id,:course_id,'queue-admin','pdf-queue@example.invalid','gemini','queued',:source_key,'over-page-limit.pdf',:source_sha256,:source_size_bytes,UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),UTC_TIMESTAMP(6))")->execute(['institution_id'=>$institutionId,'id'=>$limitId,'course_id'=>$courseId,'source_key'=>$key,'source_sha256'=>hash_file('sha256',$limitPath),'source_size_bytes'=>filesize($limitPath)]);
    putenv('CBT_APP_ENV=testing'); putenv('CBT_PDF_IMPORT_TEST_MODE=page_limit'); $limitWorker=shell_exec('"'.PHP_BINARY.'" "'.$root.DIRECTORY_SEPARATOR.'scripts'.DIRECTORY_SEPARATOR.'work_pdf_import_jobs.php"'); putenv('CBT_PDF_IMPORT_TEST_MODE'); putenv('CBT_APP_ENV'); $limit=$pdo->prepare('SELECT status,error_code FROM pdf_import_jobs WHERE institution_id=:id AND id=:job');$limit->execute(['id'=>$institutionId,'job'=>$limitId]);$limit=$limit->fetch(); if(($limit['status']??'')!=='failed'||($limit['error_code']??'')!=='page_limit') throw new RuntimeException('Page limit did not fail safely: '.$limitWorker);
    $pdo->prepare("UPDATE pdf_import_jobs SET status='queued',attempt_count=0,available_at=UTC_TIMESTAMP(6),error_code=NULL,error_message=NULL WHERE institution_id=:id AND id=:job")->execute(['id'=>$institutionId,'job'=>$limitId]); $pdo->prepare("UPDATE institution_assets SET asset_state='active',unreferenced_at=NULL,expires_at=NULL WHERE institution_id=:id AND storage_key=:key")->execute(['id'=>$institutionId,'key'=>$key]);
    putenv('CBT_APP_ENV=testing'); putenv('CBT_PDF_IMPORT_TEST_MODE=retryable'); $retryWorker=shell_exec('"'.PHP_BINARY.'" "'.$root.DIRECTORY_SEPARATOR.'scripts'.DIRECTORY_SEPARATOR.'work_pdf_import_jobs.php"'); putenv('CBT_PDF_IMPORT_TEST_MODE'); putenv('CBT_APP_ENV'); $retry=$pdo->prepare('SELECT status,error_code,attempt_count FROM pdf_import_jobs WHERE institution_id=:id AND id=:job');$retry->execute(['id'=>$institutionId,'job'=>$limitId]);$retry=$retry->fetch(); if(($retry['status']??'')!=='queued'||($retry['error_code']??'')!=='provider_unreachable'||(int)($retry['attempt_count']??0)!==1) throw new RuntimeException('Temporary provider failure was not queued for durable retry: '.$retryWorker);
    // Cancellation uses the real tenant endpoint and marks the private source for the short cleanup window.
    $csrf=queueCsrf($base,$token); $cancel=queueHttp($base.'?action=pdf-import-jobs&id='.$limitId,$token,'DELETE',null,['Cookie: CBT_ADMIN_SESSION='.$token.'; CBT_CSRF='.$csrf,'X-CSRF-Token: '.$csrf]); if($cancel['status']!==200||($cancel['body']['status']??'')!=='cancelled') throw new RuntimeException('Queued PDF cancellation failed: '.json_encode($cancel));
    $cancelled=$pdo->prepare('SELECT status,source_expires_at FROM pdf_import_jobs WHERE institution_id=:id AND id=:job');$cancelled->execute(['id'=>$institutionId,'job'=>$limitId]);$cancelled=$cancelled->fetch(); $asset=$pdo->prepare('SELECT asset_state,expires_at FROM institution_assets WHERE institution_id=:id AND storage_key=:key');$asset->execute(['id'=>$institutionId,'key'=>$key]);$asset=$asset->fetch(); if(($cancelled['status']??'')!=='cancelled'||empty($cancelled['source_expires_at'])||($asset['asset_state']??'')!=='unreferenced'||empty($asset['expires_at'])) throw new RuntimeException('Cancellation did not schedule the private PDF source for safe cleanup.');
    foreach($before as $table=>$value) if(!hash_equals($value,$hash($pdo,$table))) throw new RuntimeException("CACSA {$table} changed during queue verification.");
    $result=['pass'=>true,'institutionId'=>$institutionId,'queued'=>$jobId,'workerStatus'=>'review_ready','lowConfidenceFlag'=>true,'draftOnlyImport'=>true,'pageLimitGuard'=>true,'durableRetryGuard'=>true,'cancellationGuard'=>true,'cacsaHashes'=>'unchanged'];
} finally {
    if($pdo->inTransaction())$pdo->rollBack(); if($institutionId>1){$backupDir=$root.DIRECTORY_SEPARATOR.'database'.DIRECTORY_SEPARATOR.'backups'.DIRECTORY_SEPARATOR.'institution-'.$institutionId;if(!is_dir($backupDir))mkdir($backupDir,0700,true);file_put_contents($backupDir.DIRECTORY_SEPARATOR.'pdf-queue-test-safety-'.gmdate('Ymd-His').'.json',json_encode(['kind'=>'pdf-queue-test-safety','institutionId'=>$institutionId,'slug'=>$slug,'createdAt'=>gmdate('c')],JSON_PRETTY_PRINT),LOCK_EX);$pdo->beginTransaction();try{$pdo->prepare('DELETE FROM audit_events WHERE institution_id=:id')->execute(['id'=>$institutionId]);foreach(['pdf_import_jobs','institution_assets','backup_records','institution_settings','question_publish_targets','question_options','questions','admin_sessions','admin_users','role_permissions','roles','courses','institution_branding'] as $table)$pdo->prepare("DELETE FROM {$table} WHERE institution_id=:id")->execute(['id'=>$institutionId]);$pdo->prepare('DELETE FROM institutions WHERE id=:id AND slug=:slug')->execute(['id'=>$institutionId,'slug'=>$slug]);$pdo->commit();}catch(Throwable $e){if($pdo->inTransaction())$pdo->rollBack();throw $e;}} if($source!==''&&is_file($source))unlink($source); }
echo json_encode($result??['pass'=>false],JSON_UNESCAPED_SLASHES).PHP_EOL;
