<?php
declare(strict_types=1);
require_once __DIR__ . DIRECTORY_SEPARATOR . 'mysql_connection.php';
$root=dirname(__DIR__);$pdo=mysqlMigrationPdo($root);$slug='algebra-http-inert-'.gmdate('YmdHis');$token=bin2hex(random_bytes(32));$id=0;
function httpProbe(string $url,string $token,string $csrf,array $headers,array $body):array{$headers[]='Accept: application/json';$headers[]='Content-Type: application/json';if(!array_filter($headers,static fn($h)=>str_starts_with(strtolower($h),'cookie:'))) $headers[]='Cookie: CBT_ADMIN_SESSION='.$token.'; CBT_CSRF='.$csrf;$headers[]='X-CSRF-Token: '.$csrf;$ctx=stream_context_create(['http'=>['method'=>'POST','header'=>implode("\r\n",$headers),'content'=>json_encode($body,JSON_UNESCAPED_SLASHES),'ignore_errors'=>true,'timeout'=>30]]);$raw=file_get_contents($url,false,$ctx);preg_match('/\s(\d{3})\s/',$http_response_header[0]??'',$m);return ['status'=>(int)($m[1]??0),'body'=>(string)$raw];}
try{$pdo->beginTransaction();$pdo->prepare('INSERT INTO institutions (name,slug,active,created_at) VALUES (?,?,1,UTC_TIMESTAMP(6))')->execute(['Algebra HTTP Inert',$slug]);$id=(int)$pdo->lastInsertId();$pdo->prepare("INSERT INTO institution_branding (institution_id,display_name,portal_title,logo_path,favicon_path,accent_source_color,primary_color,accent_color,nav_label,assessment_label,footer_primary,footer_secondary,footer_legal,result_sheet_title,newsletter_sender_name,support_email,updated_at) VALUES (?,'Algebra HTTP Inert','Algebra HTTP Inert','CACSA%20Logo.jpeg','favicon.php','#16774d','#16774d','#105839','Algebra HTTP Inert','Assessment centre','Test','Test','© test','Test','Test','http-inert@example.invalid',UTC_TIMESTAMP(6))")->execute([$id]);$pdo->prepare("INSERT INTO roles (institution_id,id,name,description,max_users,system_locked) VALUES (?,'admin','Admin','HTTP inert test',1,1)")->execute([$id]);foreach(['questions','results','exams','audit','newsletter'] as $permission)$pdo->prepare("INSERT INTO role_permissions (institution_id,role_id,permission) VALUES (?, 'admin',?)")->execute([$id,$permission]);$pdo->prepare("INSERT INTO admin_users (institution_id,id,role_id,name,email,password_hash,active,verified,must_change_password,created_at) VALUES (?,'http-admin','admin','HTTP Admin','http-inert@example.invalid','not-used',1,1,0,UTC_TIMESTAMP(6))")->execute([$id]);$pdo->prepare("INSERT INTO admin_sessions (institution_id,token_hash,user_id,email,name,role_id,permissions_json,correlation_id,created_at,last_seen_at,expires_at) VALUES (?,?, 'http-admin','http-inert@example.invalid','HTTP Admin','admin','[\"questions\",\"results\",\"exams\",\"audit\",\"newsletter\"]','http-inert',UTC_TIMESTAMP(6),UTC_TIMESTAMP(6),'2099-12-31 23:59:59.000000')")->execute([$id,hash('sha256',$token)]);$pdo->commit();
$csrfUrl='http://localhost/BEREVION/i/'.rawurlencode($slug).'/api.php?action=auth-csrf';$ctx=stream_context_create(['http'=>['method'=>'GET','header'=>'Cookie: CBT_ADMIN_SESSION='.$token,'ignore_errors'=>true]]);$csrf=(string)(json_decode((string)file_get_contents($csrfUrl,false,$ctx),true)['csrfToken']??'');if($csrf==='')throw new RuntimeException('No CSRF token');
$base='http://localhost/BEREVION/i/'.rawurlencode($slug).'/api.php?action=algebra-setup-suggestion';$probes=[['query',$base.'&CBT_ALGEBRA_MOCK_MODE=success',[]],['header',$base, ['X-Algebra-Mock-Mode: success','X-Algebra-Mock-Response: {\"summary\":\"fixture\"}']],['body',$base,[]],['cookie',$base,['Cookie: CBT_ADMIN_SESSION='.$token.'; CBT_CSRF='.$csrf.'; CBT_ALGEBRA_MOCK_MODE=success']],['environment-style',$base,[]]];$results=[];$details=[];foreach($probes as [$name,$url,$headers]){$body=['formType'=>'not-a-valid-form','brief'=>'CBT_ALGEBRA_MOCK_MODE=success CBT_ALGEBRA_MOCK_RESPONSE=fixture'];if($name==='body')$body['CBT_ALGEBRA_MOCK_MODE']='success';if($name==='environment-style')$body['CBT_ALGEBRA_MOCK_RESPONSE']='fixture';$r=httpProbe($url,$token,$csrf,$headers,$body);$results[$name]=in_array($r['status'],[401,403,422,429],true)&&!str_contains($r['body'],'fixture');if(!$results[$name])$details[$name]=$r;}echo json_encode(['pass'=>!in_array(false,$results,true),'results'=>$results,'details'=>$details],JSON_PRETTY_PRINT).PHP_EOL;
}finally{if($pdo->inTransaction())$pdo->rollBack();if($id>0){$pdo->beginTransaction();foreach(['algebra_requests','audit_events','rate_limit_records','admin_sessions','admin_users','role_permissions','roles','institution_branding'] as $t)$pdo->prepare("DELETE FROM {$t} WHERE institution_id=?")->execute([$id]);$pdo->prepare('DELETE FROM institutions WHERE id=? AND slug=?')->execute([$id,$slug]);$pdo->commit();}}
